### ISSUE TITLE
Consider Flutter

### ISSUE THREAD

**Issue by ditman** [NicksPatties/timeclock#41]
This app looks perfect for Flutter! You should port it, it'd take you a fraction of the time it took you to write it natively 😅

[![Go Flutter!][meme]][flutter]

_(In case you don't want to build the pie chart on your own, [check this out too!][gems])_

🍻

[meme]: https://user-images.githubusercontent.com/1255594/226783543-0a0eead9-e78f-4706-b0de-f5303921f2d4.jpg
[flutter]: https://www.flutter.dev
[gems]: https://fluttergems.dev/plots-visualization

**Comment by NicksPatties** [comment]
Way ahead of you, buddy: https://github.com/NicksPatties/timeclock2
